# Generated by Django 4.1 on 2022-08-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='apt_num',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
