# Generated by Django 4.1 on 2022-08-31 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_shippingaddress_apt_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='apt_num',
            new_name='apt',
        ),
    ]
