# Generated by Django 4.1 on 2022-08-31 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='cusomer',
        ),
    ]
