# Generated by Django 4.1 on 2022-10-31 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_order_items_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='item',
        ),
    ]
