# Generated by Django 4.1 on 2022-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_remove_shippingaddress_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
