# Generated by Django 4.1 on 2023-01-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_shippingaddress_address_type_shippingaddress_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ('-default',), 'verbose_name_plural': 'ShippingAddresses'},
        ),
    ]
