# Generated by Django 4.1 on 2023-02-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
