# Generated by Django 4.1 on 2023-02-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_remove_order_stripe_charge_id_item_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
