# Generated by Django 4.1 on 2023-02-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_orderitem_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity_returned',
            field=models.IntegerField(default=0),
        ),
    ]
