# Generated by Django 4.1 on 2023-05-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_orderitem_partial_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
